- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' or ansible_os_family == 'AlmaLinux'
- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'


